/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CpuFeatures {
  arch: string
  brand?: string
  family?: number
  model?: number
  steppingId?: number
  flags: CpuFeaturesFlags
}
export interface CpuFeaturesFlags {
  neon: boolean
  pmull: boolean
  crc: boolean
  crypto: boolean
  aes: boolean
  sha2: boolean
  i8Mm: boolean
  v7: boolean
  vfp2: boolean
  vfp3: boolean
  vfp4: boolean
}
export function cpuFeatures(): CpuFeatures
